name: pokedex
description: Pokedex App
publish_to: 'none' 
version: 1.0.1
documentation: https://github.com/IsaelSousa/pokedex_flutter

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  audioplayers: ^0.20.1
  google_fonts: ^2.3.1
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/google_fonts/
